  #                        _ _             _
  #  _ __ ___   ___  _ __ (_) |_ ___  _ __(_)_ __   __ _
  # | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
  # | | | | | | (_) | | | | | || (_) | |  | | | | | (_| |
  # |_| |_| |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
  #                                                |___/
version: "3"
services:

  node-expoter:
    image: prom/node-exporter
    container_name: exporter
    ports:
      - "9100:9100"
    user: ":"
    networks: 
      - monitoring
    restart: unless-stopped

  #otel-collector:
  #  image: otel/opentelemetry-collector
  #  container_name: otel
  #  ports:
  #    - "4317:4317"
  #    - "55678:55678"
  #    - "8888:8888"
  #    - "4418:4418"
  #  networks: 
  #    - monitoring
  #  volumes:
  #    - ./otel/config.yml:/etc/otel/config.yml
  #  command: ["--config", "/etc/otel/config.yml"]
  #  restart: unless-stopped 

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    user: ":"
    networks: 
      - monitoring
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    restart: unless-stopped 

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: ":"
    ports:
      - "3000:3000"
    networks: 
      - monitoring
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge