  #                        _ _             _
  #  _ __ ___   ___  _ __ (_) |_ ___  _ __(_)_ __   __ _
  # | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__| | '_ \ / _` |
  # | | | | | | (_) | | | | | || (_) | |  | | | | | (_| |
  # |_| |_| |_|\___/|_| |_|_|\__\___/|_|  |_|_| |_|\__, |
  #                                                |___/
version: "3"
services:

  node-exporter:
    image: prom/node-exporter
    container_name: "node-exporter"
    ports:
      - "9100:9100"    
    networks: 
      - monitoring
    restart: unless-stopped 

  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    ports:
      - "9090:9090"    
    depends_on:
      - "node-exporter"     
    networks: 
      - monitoring     
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped 

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: "otel-collector"
    ports:      
      - "4318:4318"
    depends_on:
    - "node-exporter"
    - "prometheus"
    networks: 
      - monitoring
    volumes:
      - ./otel/config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    restart: unless-stopped 

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    user: ":"
    depends_on:
      - "node-exporter"
      - "prometheus"
      - "otel-collector"      
    ports:
      - "3000:3000"
    networks: 
      - monitoring
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/datasource.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge