{
 "title": "Celestia Node Stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DAS Total Sample (%)",
   "type": "gauge",
   "description": "DAS Total Sample (%)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * das_total_sampled_headers / das_total_sampled_headers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAS Network Height",
   "type": "gauge",
   "description": "DAS Network Height",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "das_network_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Sampled Time(s)",
   "type": "gauge",
   "description": "Last Sampled Time",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - das_latest_sampled_ts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DAS Worker",
   "type": "gauge",
   "description": "DAS Worker",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "das_busy_workers_amount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bad Encoding Count",
   "type": "timeseries",
   "description": "Bad Encoding Count",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "badencoding", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime Score(%)",
   "type": "gauge",
   "description": "Uptime Score",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*total_synced_headers/das_network_head",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PayForBlob Count",
   "type": "gauge",
   "description": "PayForBlob Count",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pfb_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last PayForBlob (minutes ago)",
   "type": "gauge",
   "description": "Last PayForBlob",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()*1000 - last_pfb_timestamp)/(1000*60)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}