{
 "title": "Infrastructure",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Server Uptime (seconds)",
   "type": "gauge",
   "description": "Server Uptime(seconds)",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk (%)",
   "type": "stat",
   "description": "Free Disk (%)",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*node_filesystem_free_bytes{mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{mountpoint=\"/etc/hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "description": "RAM Usage (%)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node-exporter\"} / node_memory_MemTotal_bytes{job=\"node-exporter\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load (%)",
   "type": "timeseries",
   "description": "CPU Load (%)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (Mbps)",
   "type": "timeseries",
   "description": "Network Traffic (Mbps)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}