receivers:  
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:3460        
processors:
  batch:

exporters:
   prometheus:
     endpoint: 0.0.0.0:6789

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]