receivers:  
  otlp:
    protocols:
      http:
        endpoint: localhost:4318' #metric celestia
  prometheus:
    config:
      scrape_configs:
        - job_name: 'node-exporter'
          scrape_interval: 30s
          static_configs:
            - targets: node-exporter:9100

processors:
  batch:

exporters:
   prometheus:
     endpoint: localhost:9090

service:
  pipelines:
    metrics:
      receivers: [otlp,prometheus]
      processors: [batch]
      exporters: [prometheus]