receivers:  
  otlp/1:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  otlp/2:
    protocols:
      http:
        endpoint: 0.0.0.0:3456  
processors:
  batch:

exporters:
   prometheus:
     endpoint: 0.0.0.0:6789

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]