receivers:  
  otlp:
    protocols:
      http:
        endpoint: localhost:4318 #metric celestia

processors:
  batch:

exporters:
   prometheus:
     endpoint: localhost:8888

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]