receivers:  
  celestia:
    protocols:
      http:
        endpoint: localhost:4318 #metric celestia

processors:
  batch:

exporters:
   prometheus:
     endpoint: host.docker.internal:8888

service:
  pipelines:
    metrics:
      receivers: [celestia]
      processors: [batch]
      exporters: [prometheus]